// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/email-signup": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/studio": {
    params: {};
  };
  "/studio/:appId": {
    params: {
      "appId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/email-signup" | "/signup" | "/studio" | "/studio/:appId";
  };
  "routes/email-signup.tsx": {
    id: "routes/email-signup";
    page: "/email-signup";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/studio.tsx": {
    id: "routes/studio";
    page: "/studio" | "/studio/:appId";
  };
  "routes/studio.$appId.tsx": {
    id: "routes/studio.$appId";
    page: "/studio/:appId";
  };
  "routes/studio._index.tsx": {
    id: "routes/studio._index";
    page: "/studio";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/email-signup": typeof import("./app/routes/email-signup.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/studio": typeof import("./app/routes/studio.tsx");
  "routes/studio.$appId": typeof import("./app/routes/studio.$appId.tsx");
  "routes/studio._index": typeof import("./app/routes/studio._index.tsx");
};